name: Cross-Platform Build and Test

on: [workflow_dispatch, pull_request]

jobs:
  build-and-test-ubuntu:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: ubuntu-latest

  build-and-test-windows:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: windows-latest

  build-and-test-macos:
    uses: ./.github/workflows/generic-jobs.yml
    with:
      os: macos-latest